### ISSUE TITLE
Password protection

### ISSUE THREAD

**Issue by Dubidubiduu** [exteon/web3backup#5]
Hey everyone,

my use case is as follows:
1. Using web3backup to create the backups of folders and databases. 
2. Two different linux machines connect via ssh download the dailys backups.

That works fine.

Problem is:
The files aren't password protected, means someone with access to my external machines also can read my backups. Very bad!

I just thought just to add a command to the tar command to encrypt the files, but apparently tar doesn't support password protection.

Just if someone wonders and want to add that function or already had added it just let me know pls.

**Comment by exteon** [comment]
Unfortunately this is currently beyond the scope for this tool. The recommended way of operation is that the backups are PUSHED to a remote secure container; you could achieve this by i.e. mounting an encrypted remote FS for the destination directory of the backup tool. But encrypting individually generated files is not something I think I'll support, especially since it raises a heapload of trouble for incremental backups. Encrypted FS's are a tried and tested method of keeping your files safe, so no need to duplicate what's already available.

**Comment by exteon** [comment]
If you absolutely need to pull the backups (as opposed to pushing), you can think of something like https://opensource.com/article/19/8/how-encrypt-files-gocryptfs or some other FUSE-based file-level encrypted filesystem to use locally to store the backup. You mount the decrypted directory as the backup target, and you sync the encrypted directory to your remote storage.
